# Generated by Django 5.2.7 on 2025-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.CharField(max_length=10)),
                ('has_kids', models.CharField(max_length=5)),
                ('travel_dates', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Travel Request',
                'verbose_name_plural': 'Travel Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
