# Generated by Django 5.2.7 on 2025-10-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(help_text='Tell us about your experience (max 300 characters)', max_length=300)),
                ('improvement', models.TextField(help_text='What could we do to improve? (max 300 characters)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Travel Feedback',
                'verbose_name_plural': 'Travel Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
